/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.7.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// checks if the SnapshotGetAllResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnapshotGetAllResponse{}

// SnapshotGetAllResponse struct for SnapshotGetAllResponse
type SnapshotGetAllResponse struct {
	Snapshot []SnapshotSnapshot `json:"snapshot,omitempty"`
}

// NewSnapshotGetAllResponse instantiates a new SnapshotGetAllResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnapshotGetAllResponse() *SnapshotGetAllResponse {
	this := SnapshotGetAllResponse{}
	return &this
}

// NewSnapshotGetAllResponseWithDefaults instantiates a new SnapshotGetAllResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnapshotGetAllResponseWithDefaults() *SnapshotGetAllResponse {
	this := SnapshotGetAllResponse{}
	return &this
}

// GetSnapshot returns the Snapshot field value if set, zero value otherwise.
func (o *SnapshotGetAllResponse) GetSnapshot() []SnapshotSnapshot {
	if o == nil || IsNil(o.Snapshot) {
		var ret []SnapshotSnapshot
		return ret
	}
	return o.Snapshot
}

// GetSnapshotOk returns a tuple with the Snapshot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnapshotGetAllResponse) GetSnapshotOk() ([]SnapshotSnapshot, bool) {
	if o == nil || IsNil(o.Snapshot) {
		return nil, false
	}
	return o.Snapshot, true
}

// HasSnapshot returns a boolean if a field has been set.
func (o *SnapshotGetAllResponse) HasSnapshot() bool {
	if o != nil && !IsNil(o.Snapshot) {
		return true
	}

	return false
}

// SetSnapshot gets a reference to the given []SnapshotSnapshot and assigns it to the Snapshot field.
func (o *SnapshotGetAllResponse) SetSnapshot(v []SnapshotSnapshot) {
	o.Snapshot = v
}

func (o SnapshotGetAllResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnapshotGetAllResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Snapshot) {
		toSerialize["snapshot"] = o.Snapshot
	}
	return toSerialize, nil
}

type NullableSnapshotGetAllResponse struct {
	value *SnapshotGetAllResponse
	isSet bool
}

func (v NullableSnapshotGetAllResponse) Get() *SnapshotGetAllResponse {
	return v.value
}

func (v *NullableSnapshotGetAllResponse) Set(val *SnapshotGetAllResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSnapshotGetAllResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSnapshotGetAllResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnapshotGetAllResponse(val *SnapshotGetAllResponse) *NullableSnapshotGetAllResponse {
	return &NullableSnapshotGetAllResponse{value: val, isSet: true}
}

func (v NullableSnapshotGetAllResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnapshotGetAllResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


