/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.7.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// checks if the ConfiguratorRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfiguratorRange{}

// ConfiguratorRange struct for ConfiguratorRange
type ConfiguratorRange struct {
	Min *int32 `json:"min,omitempty"`
	Max *int32 `json:"max,omitempty"`
}

// NewConfiguratorRange instantiates a new ConfiguratorRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfiguratorRange() *ConfiguratorRange {
	this := ConfiguratorRange{}
	return &this
}

// NewConfiguratorRangeWithDefaults instantiates a new ConfiguratorRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfiguratorRangeWithDefaults() *ConfiguratorRange {
	this := ConfiguratorRange{}
	return &this
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *ConfiguratorRange) GetMin() int32 {
	if o == nil || IsNil(o.Min) {
		var ret int32
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfiguratorRange) GetMinOk() (*int32, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *ConfiguratorRange) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given int32 and assigns it to the Min field.
func (o *ConfiguratorRange) SetMin(v int32) {
	o.Min = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *ConfiguratorRange) GetMax() int32 {
	if o == nil || IsNil(o.Max) {
		var ret int32
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfiguratorRange) GetMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *ConfiguratorRange) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given int32 and assigns it to the Max field.
func (o *ConfiguratorRange) SetMax(v int32) {
	o.Max = &v
}

func (o ConfiguratorRange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfiguratorRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	return toSerialize, nil
}

type NullableConfiguratorRange struct {
	value *ConfiguratorRange
	isSet bool
}

func (v NullableConfiguratorRange) Get() *ConfiguratorRange {
	return v.value
}

func (v *NullableConfiguratorRange) Set(val *ConfiguratorRange) {
	v.value = val
	v.isSet = true
}

func (v NullableConfiguratorRange) IsSet() bool {
	return v.isSet
}

func (v *NullableConfiguratorRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfiguratorRange(val *ConfiguratorRange) *NullableConfiguratorRange {
	return &NullableConfiguratorRange{value: val, isSet: true}
}

func (v NullableConfiguratorRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfiguratorRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


