/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.7.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// checks if the NetworkRemovePrivateNetworkResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkRemovePrivateNetworkResponseError{}

// NetworkRemovePrivateNetworkResponseError struct for NetworkRemovePrivateNetworkResponseError
type NetworkRemovePrivateNetworkResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	VpsNetworkUse *NetworkRemovePrivateNetworkResponseErrorVpsNetworkUseError `json:"vps_network_use,omitempty"`
}

// NewNetworkRemovePrivateNetworkResponseError instantiates a new NetworkRemovePrivateNetworkResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkRemovePrivateNetworkResponseError() *NetworkRemovePrivateNetworkResponseError {
	this := NetworkRemovePrivateNetworkResponseError{}
	return &this
}

// NewNetworkRemovePrivateNetworkResponseErrorWithDefaults instantiates a new NetworkRemovePrivateNetworkResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkRemovePrivateNetworkResponseErrorWithDefaults() *NetworkRemovePrivateNetworkResponseError {
	this := NetworkRemovePrivateNetworkResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *NetworkRemovePrivateNetworkResponseError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkRemovePrivateNetworkResponseError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *NetworkRemovePrivateNetworkResponseError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *NetworkRemovePrivateNetworkResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *NetworkRemovePrivateNetworkResponseError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkRemovePrivateNetworkResponseError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *NetworkRemovePrivateNetworkResponseError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *NetworkRemovePrivateNetworkResponseError) SetMessage(v string) {
	o.Message = &v
}

// GetVpsNetworkUse returns the VpsNetworkUse field value if set, zero value otherwise.
func (o *NetworkRemovePrivateNetworkResponseError) GetVpsNetworkUse() NetworkRemovePrivateNetworkResponseErrorVpsNetworkUseError {
	if o == nil || IsNil(o.VpsNetworkUse) {
		var ret NetworkRemovePrivateNetworkResponseErrorVpsNetworkUseError
		return ret
	}
	return *o.VpsNetworkUse
}

// GetVpsNetworkUseOk returns a tuple with the VpsNetworkUse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkRemovePrivateNetworkResponseError) GetVpsNetworkUseOk() (*NetworkRemovePrivateNetworkResponseErrorVpsNetworkUseError, bool) {
	if o == nil || IsNil(o.VpsNetworkUse) {
		return nil, false
	}
	return o.VpsNetworkUse, true
}

// HasVpsNetworkUse returns a boolean if a field has been set.
func (o *NetworkRemovePrivateNetworkResponseError) HasVpsNetworkUse() bool {
	if o != nil && !IsNil(o.VpsNetworkUse) {
		return true
	}

	return false
}

// SetVpsNetworkUse gets a reference to the given NetworkRemovePrivateNetworkResponseErrorVpsNetworkUseError and assigns it to the VpsNetworkUse field.
func (o *NetworkRemovePrivateNetworkResponseError) SetVpsNetworkUse(v NetworkRemovePrivateNetworkResponseErrorVpsNetworkUseError) {
	o.VpsNetworkUse = &v
}

func (o NetworkRemovePrivateNetworkResponseError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkRemovePrivateNetworkResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.VpsNetworkUse) {
		toSerialize["vps_network_use"] = o.VpsNetworkUse
	}
	return toSerialize, nil
}

type NullableNetworkRemovePrivateNetworkResponseError struct {
	value *NetworkRemovePrivateNetworkResponseError
	isSet bool
}

func (v NullableNetworkRemovePrivateNetworkResponseError) Get() *NetworkRemovePrivateNetworkResponseError {
	return v.value
}

func (v *NullableNetworkRemovePrivateNetworkResponseError) Set(val *NetworkRemovePrivateNetworkResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkRemovePrivateNetworkResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkRemovePrivateNetworkResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkRemovePrivateNetworkResponseError(val *NetworkRemovePrivateNetworkResponseError) *NullableNetworkRemovePrivateNetworkResponseError {
	return &NullableNetworkRemovePrivateNetworkResponseError{value: val, isSet: true}
}

func (v NullableNetworkRemovePrivateNetworkResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkRemovePrivateNetworkResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


