/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// NetworkOrderIpAddressRequest struct for NetworkOrderIpAddressRequest
type NetworkOrderIpAddressRequest struct {
	Id *string `json:"id,omitempty"`
}

// NewNetworkOrderIpAddressRequest instantiates a new NetworkOrderIpAddressRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkOrderIpAddressRequest() *NetworkOrderIpAddressRequest {
	this := NetworkOrderIpAddressRequest{}
	return &this
}

// NewNetworkOrderIpAddressRequestWithDefaults instantiates a new NetworkOrderIpAddressRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkOrderIpAddressRequestWithDefaults() *NetworkOrderIpAddressRequest {
	this := NetworkOrderIpAddressRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NetworkOrderIpAddressRequest) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkOrderIpAddressRequest) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NetworkOrderIpAddressRequest) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NetworkOrderIpAddressRequest) SetId(v string) {
	o.Id = &v
}

func (o NetworkOrderIpAddressRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableNetworkOrderIpAddressRequest struct {
	value *NetworkOrderIpAddressRequest
	isSet bool
}

func (v NullableNetworkOrderIpAddressRequest) Get() *NetworkOrderIpAddressRequest {
	return v.value
}

func (v *NullableNetworkOrderIpAddressRequest) Set(val *NetworkOrderIpAddressRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkOrderIpAddressRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkOrderIpAddressRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkOrderIpAddressRequest(val *NetworkOrderIpAddressRequest) *NullableNetworkOrderIpAddressRequest {
	return &NullableNetworkOrderIpAddressRequest{value: val, isSet: true}
}

func (v NullableNetworkOrderIpAddressRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkOrderIpAddressRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


