/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// BackupGetOrdersResponse struct for BackupGetOrdersResponse
type BackupGetOrdersResponse struct {
	Order []StructuresOrderInfo `json:"order,omitempty"`
}

// NewBackupGetOrdersResponse instantiates a new BackupGetOrdersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupGetOrdersResponse() *BackupGetOrdersResponse {
	this := BackupGetOrdersResponse{}
	return &this
}

// NewBackupGetOrdersResponseWithDefaults instantiates a new BackupGetOrdersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupGetOrdersResponseWithDefaults() *BackupGetOrdersResponse {
	this := BackupGetOrdersResponse{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *BackupGetOrdersResponse) GetOrder() []StructuresOrderInfo {
	if o == nil || isNil(o.Order) {
		var ret []StructuresOrderInfo
		return ret
	}
	return o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupGetOrdersResponse) GetOrderOk() ([]StructuresOrderInfo, bool) {
	if o == nil || isNil(o.Order) {
    return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *BackupGetOrdersResponse) HasOrder() bool {
	if o != nil && !isNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given []StructuresOrderInfo and assigns it to the Order field.
func (o *BackupGetOrdersResponse) SetOrder(v []StructuresOrderInfo) {
	o.Order = v
}

func (o BackupGetOrdersResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	return json.Marshal(toSerialize)
}

type NullableBackupGetOrdersResponse struct {
	value *BackupGetOrdersResponse
	isSet bool
}

func (v NullableBackupGetOrdersResponse) Get() *BackupGetOrdersResponse {
	return v.value
}

func (v *NullableBackupGetOrdersResponse) Set(val *BackupGetOrdersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupGetOrdersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupGetOrdersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupGetOrdersResponse(val *BackupGetOrdersResponse) *NullableBackupGetOrdersResponse {
	return &NullableBackupGetOrdersResponse{value: val, isSet: true}
}

func (v NullableBackupGetOrdersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupGetOrdersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


