/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.7.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// checks if the StructuresAdditionalIpInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StructuresAdditionalIpInfo{}

// StructuresAdditionalIpInfo struct for StructuresAdditionalIpInfo
type StructuresAdditionalIpInfo struct {
	Ip *string `json:"ip,omitempty"`
	VpsId *string `json:"vps_id,omitempty"`
	Region *string `json:"region,omitempty"`
}

// NewStructuresAdditionalIpInfo instantiates a new StructuresAdditionalIpInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStructuresAdditionalIpInfo() *StructuresAdditionalIpInfo {
	this := StructuresAdditionalIpInfo{}
	return &this
}

// NewStructuresAdditionalIpInfoWithDefaults instantiates a new StructuresAdditionalIpInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStructuresAdditionalIpInfoWithDefaults() *StructuresAdditionalIpInfo {
	this := StructuresAdditionalIpInfo{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *StructuresAdditionalIpInfo) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructuresAdditionalIpInfo) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *StructuresAdditionalIpInfo) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *StructuresAdditionalIpInfo) SetIp(v string) {
	o.Ip = &v
}

// GetVpsId returns the VpsId field value if set, zero value otherwise.
func (o *StructuresAdditionalIpInfo) GetVpsId() string {
	if o == nil || IsNil(o.VpsId) {
		var ret string
		return ret
	}
	return *o.VpsId
}

// GetVpsIdOk returns a tuple with the VpsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructuresAdditionalIpInfo) GetVpsIdOk() (*string, bool) {
	if o == nil || IsNil(o.VpsId) {
		return nil, false
	}
	return o.VpsId, true
}

// HasVpsId returns a boolean if a field has been set.
func (o *StructuresAdditionalIpInfo) HasVpsId() bool {
	if o != nil && !IsNil(o.VpsId) {
		return true
	}

	return false
}

// SetVpsId gets a reference to the given string and assigns it to the VpsId field.
func (o *StructuresAdditionalIpInfo) SetVpsId(v string) {
	o.VpsId = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *StructuresAdditionalIpInfo) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructuresAdditionalIpInfo) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *StructuresAdditionalIpInfo) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *StructuresAdditionalIpInfo) SetRegion(v string) {
	o.Region = &v
}

func (o StructuresAdditionalIpInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StructuresAdditionalIpInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.VpsId) {
		toSerialize["vps_id"] = o.VpsId
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	return toSerialize, nil
}

type NullableStructuresAdditionalIpInfo struct {
	value *StructuresAdditionalIpInfo
	isSet bool
}

func (v NullableStructuresAdditionalIpInfo) Get() *StructuresAdditionalIpInfo {
	return v.value
}

func (v *NullableStructuresAdditionalIpInfo) Set(val *StructuresAdditionalIpInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableStructuresAdditionalIpInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableStructuresAdditionalIpInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStructuresAdditionalIpInfo(val *StructuresAdditionalIpInfo) *NullableStructuresAdditionalIpInfo {
	return &NullableStructuresAdditionalIpInfo{value: val, isSet: true}
}

func (v NullableStructuresAdditionalIpInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStructuresAdditionalIpInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


