/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.7.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// NetworkCreatePrivateNetworkRequest struct for NetworkCreatePrivateNetworkRequest
type NetworkCreatePrivateNetworkRequest struct {
	Region *string `json:"region,omitempty"`
}

// NewNetworkCreatePrivateNetworkRequest instantiates a new NetworkCreatePrivateNetworkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkCreatePrivateNetworkRequest() *NetworkCreatePrivateNetworkRequest {
	this := NetworkCreatePrivateNetworkRequest{}
	return &this
}

// NewNetworkCreatePrivateNetworkRequestWithDefaults instantiates a new NetworkCreatePrivateNetworkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkCreatePrivateNetworkRequestWithDefaults() *NetworkCreatePrivateNetworkRequest {
	this := NetworkCreatePrivateNetworkRequest{}
	return &this
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *NetworkCreatePrivateNetworkRequest) GetRegion() string {
	if o == nil || isNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkCreatePrivateNetworkRequest) GetRegionOk() (*string, bool) {
	if o == nil || isNil(o.Region) {
    return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *NetworkCreatePrivateNetworkRequest) HasRegion() bool {
	if o != nil && !isNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *NetworkCreatePrivateNetworkRequest) SetRegion(v string) {
	o.Region = &v
}

func (o NetworkCreatePrivateNetworkRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	return json.Marshal(toSerialize)
}

type NullableNetworkCreatePrivateNetworkRequest struct {
	value *NetworkCreatePrivateNetworkRequest
	isSet bool
}

func (v NullableNetworkCreatePrivateNetworkRequest) Get() *NetworkCreatePrivateNetworkRequest {
	return v.value
}

func (v *NullableNetworkCreatePrivateNetworkRequest) Set(val *NetworkCreatePrivateNetworkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkCreatePrivateNetworkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkCreatePrivateNetworkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkCreatePrivateNetworkRequest(val *NetworkCreatePrivateNetworkRequest) *NullableNetworkCreatePrivateNetworkRequest {
	return &NullableNetworkCreatePrivateNetworkRequest{value: val, isSet: true}
}

func (v NullableNetworkCreatePrivateNetworkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkCreatePrivateNetworkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


