/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.7.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// checks if the ManageChangePinnedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManageChangePinnedResponse{}

// ManageChangePinnedResponse struct for ManageChangePinnedResponse
type ManageChangePinnedResponse struct {
	Vps *ManageVpsInfo `json:"vps,omitempty"`
	Error *ManageChangePinnedResponseError `json:"error,omitempty"`
}

// NewManageChangePinnedResponse instantiates a new ManageChangePinnedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageChangePinnedResponse() *ManageChangePinnedResponse {
	this := ManageChangePinnedResponse{}
	return &this
}

// NewManageChangePinnedResponseWithDefaults instantiates a new ManageChangePinnedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageChangePinnedResponseWithDefaults() *ManageChangePinnedResponse {
	this := ManageChangePinnedResponse{}
	return &this
}

// GetVps returns the Vps field value if set, zero value otherwise.
func (o *ManageChangePinnedResponse) GetVps() ManageVpsInfo {
	if o == nil || IsNil(o.Vps) {
		var ret ManageVpsInfo
		return ret
	}
	return *o.Vps
}

// GetVpsOk returns a tuple with the Vps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageChangePinnedResponse) GetVpsOk() (*ManageVpsInfo, bool) {
	if o == nil || IsNil(o.Vps) {
		return nil, false
	}
	return o.Vps, true
}

// HasVps returns a boolean if a field has been set.
func (o *ManageChangePinnedResponse) HasVps() bool {
	if o != nil && !IsNil(o.Vps) {
		return true
	}

	return false
}

// SetVps gets a reference to the given ManageVpsInfo and assigns it to the Vps field.
func (o *ManageChangePinnedResponse) SetVps(v ManageVpsInfo) {
	o.Vps = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ManageChangePinnedResponse) GetError() ManageChangePinnedResponseError {
	if o == nil || IsNil(o.Error) {
		var ret ManageChangePinnedResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageChangePinnedResponse) GetErrorOk() (*ManageChangePinnedResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ManageChangePinnedResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ManageChangePinnedResponseError and assigns it to the Error field.
func (o *ManageChangePinnedResponse) SetError(v ManageChangePinnedResponseError) {
	o.Error = &v
}

func (o ManageChangePinnedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManageChangePinnedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Vps) {
		toSerialize["vps"] = o.Vps
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableManageChangePinnedResponse struct {
	value *ManageChangePinnedResponse
	isSet bool
}

func (v NullableManageChangePinnedResponse) Get() *ManageChangePinnedResponse {
	return v.value
}

func (v *NullableManageChangePinnedResponse) Set(val *ManageChangePinnedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableManageChangePinnedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableManageChangePinnedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageChangePinnedResponse(val *ManageChangePinnedResponse) *NullableManageChangePinnedResponse {
	return &NullableManageChangePinnedResponse{value: val, isSet: true}
}

func (v NullableManageChangePinnedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageChangePinnedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


