/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// ManageUpdateInfoResponse struct for ManageUpdateInfoResponse
type ManageUpdateInfoResponse struct {
	Vps *ManageVpsInfo `json:"vps,omitempty"`
	Error *ManageUpdateInfoResponseError `json:"error,omitempty"`
}

// NewManageUpdateInfoResponse instantiates a new ManageUpdateInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageUpdateInfoResponse() *ManageUpdateInfoResponse {
	this := ManageUpdateInfoResponse{}
	return &this
}

// NewManageUpdateInfoResponseWithDefaults instantiates a new ManageUpdateInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageUpdateInfoResponseWithDefaults() *ManageUpdateInfoResponse {
	this := ManageUpdateInfoResponse{}
	return &this
}

// GetVps returns the Vps field value if set, zero value otherwise.
func (o *ManageUpdateInfoResponse) GetVps() ManageVpsInfo {
	if o == nil || isNil(o.Vps) {
		var ret ManageVpsInfo
		return ret
	}
	return *o.Vps
}

// GetVpsOk returns a tuple with the Vps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageUpdateInfoResponse) GetVpsOk() (*ManageVpsInfo, bool) {
	if o == nil || isNil(o.Vps) {
    return nil, false
	}
	return o.Vps, true
}

// HasVps returns a boolean if a field has been set.
func (o *ManageUpdateInfoResponse) HasVps() bool {
	if o != nil && !isNil(o.Vps) {
		return true
	}

	return false
}

// SetVps gets a reference to the given ManageVpsInfo and assigns it to the Vps field.
func (o *ManageUpdateInfoResponse) SetVps(v ManageVpsInfo) {
	o.Vps = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ManageUpdateInfoResponse) GetError() ManageUpdateInfoResponseError {
	if o == nil || isNil(o.Error) {
		var ret ManageUpdateInfoResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageUpdateInfoResponse) GetErrorOk() (*ManageUpdateInfoResponseError, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ManageUpdateInfoResponse) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ManageUpdateInfoResponseError and assigns it to the Error field.
func (o *ManageUpdateInfoResponse) SetError(v ManageUpdateInfoResponseError) {
	o.Error = &v
}

func (o ManageUpdateInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Vps) {
		toSerialize["vps"] = o.Vps
	}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableManageUpdateInfoResponse struct {
	value *ManageUpdateInfoResponse
	isSet bool
}

func (v NullableManageUpdateInfoResponse) Get() *ManageUpdateInfoResponse {
	return v.value
}

func (v *NullableManageUpdateInfoResponse) Set(val *ManageUpdateInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableManageUpdateInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableManageUpdateInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageUpdateInfoResponse(val *ManageUpdateInfoResponse) *NullableManageUpdateInfoResponse {
	return &NullableManageUpdateInfoResponse{value: val, isSet: true}
}

func (v NullableManageUpdateInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageUpdateInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


