/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.7.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// checks if the ManageVpsConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManageVpsConfiguration{}

// ManageVpsConfiguration struct for ManageVpsConfiguration
type ManageVpsConfiguration struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	CpuCount *int32 `json:"cpu_count,omitempty"`
	DiskSize *int32 `json:"disk_size,omitempty"`
	Memory *int32 `json:"memory,omitempty"`
	BandwidthPublic *int32 `json:"bandwidth_public,omitempty"`
	PriceDay *float64 `json:"price_day,omitempty"`
	PriceMonth *float64 `json:"price_month,omitempty"`
	Available *bool `json:"available,omitempty"`
	Custom *bool `json:"custom,omitempty"`
	Configurable *bool `json:"configurable,omitempty"`
	Region *string `json:"region,omitempty"`
	Group *string `json:"group,omitempty"`
}

// NewManageVpsConfiguration instantiates a new ManageVpsConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageVpsConfiguration() *ManageVpsConfiguration {
	this := ManageVpsConfiguration{}
	return &this
}

// NewManageVpsConfigurationWithDefaults instantiates a new ManageVpsConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageVpsConfigurationWithDefaults() *ManageVpsConfiguration {
	this := ManageVpsConfiguration{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ManageVpsConfiguration) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ManageVpsConfiguration) SetName(v string) {
	o.Name = &v
}

// GetCpuCount returns the CpuCount field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetCpuCount() int32 {
	if o == nil || IsNil(o.CpuCount) {
		var ret int32
		return ret
	}
	return *o.CpuCount
}

// GetCpuCountOk returns a tuple with the CpuCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetCpuCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CpuCount) {
		return nil, false
	}
	return o.CpuCount, true
}

// HasCpuCount returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasCpuCount() bool {
	if o != nil && !IsNil(o.CpuCount) {
		return true
	}

	return false
}

// SetCpuCount gets a reference to the given int32 and assigns it to the CpuCount field.
func (o *ManageVpsConfiguration) SetCpuCount(v int32) {
	o.CpuCount = &v
}

// GetDiskSize returns the DiskSize field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetDiskSize() int32 {
	if o == nil || IsNil(o.DiskSize) {
		var ret int32
		return ret
	}
	return *o.DiskSize
}

// GetDiskSizeOk returns a tuple with the DiskSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetDiskSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.DiskSize) {
		return nil, false
	}
	return o.DiskSize, true
}

// HasDiskSize returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasDiskSize() bool {
	if o != nil && !IsNil(o.DiskSize) {
		return true
	}

	return false
}

// SetDiskSize gets a reference to the given int32 and assigns it to the DiskSize field.
func (o *ManageVpsConfiguration) SetDiskSize(v int32) {
	o.DiskSize = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetMemory() int32 {
	if o == nil || IsNil(o.Memory) {
		var ret int32
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given int32 and assigns it to the Memory field.
func (o *ManageVpsConfiguration) SetMemory(v int32) {
	o.Memory = &v
}

// GetBandwidthPublic returns the BandwidthPublic field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetBandwidthPublic() int32 {
	if o == nil || IsNil(o.BandwidthPublic) {
		var ret int32
		return ret
	}
	return *o.BandwidthPublic
}

// GetBandwidthPublicOk returns a tuple with the BandwidthPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetBandwidthPublicOk() (*int32, bool) {
	if o == nil || IsNil(o.BandwidthPublic) {
		return nil, false
	}
	return o.BandwidthPublic, true
}

// HasBandwidthPublic returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasBandwidthPublic() bool {
	if o != nil && !IsNil(o.BandwidthPublic) {
		return true
	}

	return false
}

// SetBandwidthPublic gets a reference to the given int32 and assigns it to the BandwidthPublic field.
func (o *ManageVpsConfiguration) SetBandwidthPublic(v int32) {
	o.BandwidthPublic = &v
}

// GetPriceDay returns the PriceDay field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetPriceDay() float64 {
	if o == nil || IsNil(o.PriceDay) {
		var ret float64
		return ret
	}
	return *o.PriceDay
}

// GetPriceDayOk returns a tuple with the PriceDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetPriceDayOk() (*float64, bool) {
	if o == nil || IsNil(o.PriceDay) {
		return nil, false
	}
	return o.PriceDay, true
}

// HasPriceDay returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasPriceDay() bool {
	if o != nil && !IsNil(o.PriceDay) {
		return true
	}

	return false
}

// SetPriceDay gets a reference to the given float64 and assigns it to the PriceDay field.
func (o *ManageVpsConfiguration) SetPriceDay(v float64) {
	o.PriceDay = &v
}

// GetPriceMonth returns the PriceMonth field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetPriceMonth() float64 {
	if o == nil || IsNil(o.PriceMonth) {
		var ret float64
		return ret
	}
	return *o.PriceMonth
}

// GetPriceMonthOk returns a tuple with the PriceMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetPriceMonthOk() (*float64, bool) {
	if o == nil || IsNil(o.PriceMonth) {
		return nil, false
	}
	return o.PriceMonth, true
}

// HasPriceMonth returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasPriceMonth() bool {
	if o != nil && !IsNil(o.PriceMonth) {
		return true
	}

	return false
}

// SetPriceMonth gets a reference to the given float64 and assigns it to the PriceMonth field.
func (o *ManageVpsConfiguration) SetPriceMonth(v float64) {
	o.PriceMonth = &v
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetAvailable() bool {
	if o == nil || IsNil(o.Available) {
		var ret bool
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetAvailableOk() (*bool, bool) {
	if o == nil || IsNil(o.Available) {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasAvailable() bool {
	if o != nil && !IsNil(o.Available) {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given bool and assigns it to the Available field.
func (o *ManageVpsConfiguration) SetAvailable(v bool) {
	o.Available = &v
}

// GetCustom returns the Custom field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetCustom() bool {
	if o == nil || IsNil(o.Custom) {
		var ret bool
		return ret
	}
	return *o.Custom
}

// GetCustomOk returns a tuple with the Custom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetCustomOk() (*bool, bool) {
	if o == nil || IsNil(o.Custom) {
		return nil, false
	}
	return o.Custom, true
}

// HasCustom returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasCustom() bool {
	if o != nil && !IsNil(o.Custom) {
		return true
	}

	return false
}

// SetCustom gets a reference to the given bool and assigns it to the Custom field.
func (o *ManageVpsConfiguration) SetCustom(v bool) {
	o.Custom = &v
}

// GetConfigurable returns the Configurable field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetConfigurable() bool {
	if o == nil || IsNil(o.Configurable) {
		var ret bool
		return ret
	}
	return *o.Configurable
}

// GetConfigurableOk returns a tuple with the Configurable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetConfigurableOk() (*bool, bool) {
	if o == nil || IsNil(o.Configurable) {
		return nil, false
	}
	return o.Configurable, true
}

// HasConfigurable returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasConfigurable() bool {
	if o != nil && !IsNil(o.Configurable) {
		return true
	}

	return false
}

// SetConfigurable gets a reference to the given bool and assigns it to the Configurable field.
func (o *ManageVpsConfiguration) SetConfigurable(v bool) {
	o.Configurable = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *ManageVpsConfiguration) SetRegion(v string) {
	o.Region = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *ManageVpsConfiguration) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageVpsConfiguration) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *ManageVpsConfiguration) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *ManageVpsConfiguration) SetGroup(v string) {
	o.Group = &v
}

func (o ManageVpsConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManageVpsConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CpuCount) {
		toSerialize["cpu_count"] = o.CpuCount
	}
	if !IsNil(o.DiskSize) {
		toSerialize["disk_size"] = o.DiskSize
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.BandwidthPublic) {
		toSerialize["bandwidth_public"] = o.BandwidthPublic
	}
	if !IsNil(o.PriceDay) {
		toSerialize["price_day"] = o.PriceDay
	}
	if !IsNil(o.PriceMonth) {
		toSerialize["price_month"] = o.PriceMonth
	}
	if !IsNil(o.Available) {
		toSerialize["available"] = o.Available
	}
	if !IsNil(o.Custom) {
		toSerialize["custom"] = o.Custom
	}
	if !IsNil(o.Configurable) {
		toSerialize["configurable"] = o.Configurable
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	return toSerialize, nil
}

type NullableManageVpsConfiguration struct {
	value *ManageVpsConfiguration
	isSet bool
}

func (v NullableManageVpsConfiguration) Get() *ManageVpsConfiguration {
	return v.value
}

func (v *NullableManageVpsConfiguration) Set(val *ManageVpsConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableManageVpsConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableManageVpsConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageVpsConfiguration(val *ManageVpsConfiguration) *NullableManageVpsConfiguration {
	return &NullableManageVpsConfiguration{value: val, isSet: true}
}

func (v NullableManageVpsConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageVpsConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


