/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// BackupRestoreFileResponse struct for BackupRestoreFileResponse
type BackupRestoreFileResponse struct {
	Order *StructuresOrderInfo `json:"order,omitempty"`
	Error *BackupRestoreFileResponseError `json:"error,omitempty"`
}

// NewBackupRestoreFileResponse instantiates a new BackupRestoreFileResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupRestoreFileResponse() *BackupRestoreFileResponse {
	this := BackupRestoreFileResponse{}
	return &this
}

// NewBackupRestoreFileResponseWithDefaults instantiates a new BackupRestoreFileResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupRestoreFileResponseWithDefaults() *BackupRestoreFileResponse {
	this := BackupRestoreFileResponse{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *BackupRestoreFileResponse) GetOrder() StructuresOrderInfo {
	if o == nil || isNil(o.Order) {
		var ret StructuresOrderInfo
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupRestoreFileResponse) GetOrderOk() (*StructuresOrderInfo, bool) {
	if o == nil || isNil(o.Order) {
    return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *BackupRestoreFileResponse) HasOrder() bool {
	if o != nil && !isNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given StructuresOrderInfo and assigns it to the Order field.
func (o *BackupRestoreFileResponse) SetOrder(v StructuresOrderInfo) {
	o.Order = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *BackupRestoreFileResponse) GetError() BackupRestoreFileResponseError {
	if o == nil || isNil(o.Error) {
		var ret BackupRestoreFileResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupRestoreFileResponse) GetErrorOk() (*BackupRestoreFileResponseError, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *BackupRestoreFileResponse) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given BackupRestoreFileResponseError and assigns it to the Error field.
func (o *BackupRestoreFileResponse) SetError(v BackupRestoreFileResponseError) {
	o.Error = &v
}

func (o BackupRestoreFileResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableBackupRestoreFileResponse struct {
	value *BackupRestoreFileResponse
	isSet bool
}

func (v NullableBackupRestoreFileResponse) Get() *BackupRestoreFileResponse {
	return v.value
}

func (v *NullableBackupRestoreFileResponse) Set(val *BackupRestoreFileResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupRestoreFileResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupRestoreFileResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupRestoreFileResponse(val *BackupRestoreFileResponse) *NullableBackupRestoreFileResponse {
	return &NullableBackupRestoreFileResponse{value: val, isSet: true}
}

func (v NullableBackupRestoreFileResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupRestoreFileResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


