/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.7.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// checks if the StatisticGetCpuResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatisticGetCpuResponse{}

// StatisticGetCpuResponse struct for StatisticGetCpuResponse
type StatisticGetCpuResponse struct {
	Cpu *StatisticSeriesData `json:"cpu,omitempty"`
}

// NewStatisticGetCpuResponse instantiates a new StatisticGetCpuResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatisticGetCpuResponse() *StatisticGetCpuResponse {
	this := StatisticGetCpuResponse{}
	return &this
}

// NewStatisticGetCpuResponseWithDefaults instantiates a new StatisticGetCpuResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatisticGetCpuResponseWithDefaults() *StatisticGetCpuResponse {
	this := StatisticGetCpuResponse{}
	return &this
}

// GetCpu returns the Cpu field value if set, zero value otherwise.
func (o *StatisticGetCpuResponse) GetCpu() StatisticSeriesData {
	if o == nil || IsNil(o.Cpu) {
		var ret StatisticSeriesData
		return ret
	}
	return *o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticGetCpuResponse) GetCpuOk() (*StatisticSeriesData, bool) {
	if o == nil || IsNil(o.Cpu) {
		return nil, false
	}
	return o.Cpu, true
}

// HasCpu returns a boolean if a field has been set.
func (o *StatisticGetCpuResponse) HasCpu() bool {
	if o != nil && !IsNil(o.Cpu) {
		return true
	}

	return false
}

// SetCpu gets a reference to the given StatisticSeriesData and assigns it to the Cpu field.
func (o *StatisticGetCpuResponse) SetCpu(v StatisticSeriesData) {
	o.Cpu = &v
}

func (o StatisticGetCpuResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatisticGetCpuResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cpu) {
		toSerialize["cpu"] = o.Cpu
	}
	return toSerialize, nil
}

type NullableStatisticGetCpuResponse struct {
	value *StatisticGetCpuResponse
	isSet bool
}

func (v NullableStatisticGetCpuResponse) Get() *StatisticGetCpuResponse {
	return v.value
}

func (v *NullableStatisticGetCpuResponse) Set(val *StatisticGetCpuResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStatisticGetCpuResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStatisticGetCpuResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatisticGetCpuResponse(val *StatisticGetCpuResponse) *NullableStatisticGetCpuResponse {
	return &NullableStatisticGetCpuResponse{value: val, isSet: true}
}

func (v NullableStatisticGetCpuResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatisticGetCpuResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


