/*
API Облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps

import (
	"encoding/json"
)

// ManageDetachSshKeyResponseError struct for ManageDetachSshKeyResponseError
type ManageDetachSshKeyResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewManageDetachSshKeyResponseError instantiates a new ManageDetachSshKeyResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageDetachSshKeyResponseError() *ManageDetachSshKeyResponseError {
	this := ManageDetachSshKeyResponseError{}
	return &this
}

// NewManageDetachSshKeyResponseErrorWithDefaults instantiates a new ManageDetachSshKeyResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageDetachSshKeyResponseErrorWithDefaults() *ManageDetachSshKeyResponseError {
	this := ManageDetachSshKeyResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ManageDetachSshKeyResponseError) GetCode() string {
	if o == nil || isNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageDetachSshKeyResponseError) GetCodeOk() (*string, bool) {
	if o == nil || isNil(o.Code) {
    return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ManageDetachSshKeyResponseError) HasCode() bool {
	if o != nil && !isNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ManageDetachSshKeyResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ManageDetachSshKeyResponseError) GetMessage() string {
	if o == nil || isNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageDetachSshKeyResponseError) GetMessageOk() (*string, bool) {
	if o == nil || isNil(o.Message) {
    return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ManageDetachSshKeyResponseError) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ManageDetachSshKeyResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o ManageDetachSshKeyResponseError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableManageDetachSshKeyResponseError struct {
	value *ManageDetachSshKeyResponseError
	isSet bool
}

func (v NullableManageDetachSshKeyResponseError) Get() *ManageDetachSshKeyResponseError {
	return v.value
}

func (v *NullableManageDetachSshKeyResponseError) Set(val *ManageDetachSshKeyResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableManageDetachSshKeyResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableManageDetachSshKeyResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageDetachSshKeyResponseError(val *ManageDetachSshKeyResponseError) *NullableManageDetachSshKeyResponseError {
	return &NullableManageDetachSshKeyResponseError{value: val, isSet: true}
}

func (v NullableManageDetachSshKeyResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageDetachSshKeyResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


